### ISSUE TITLE
changing "graylog::repository -> $version" has no effect

### ISSUE THREAD

**Issue by nomoresecrets** [Graylog2/puppet-graylog#10]
Hi,

I'm using v0.2.1 of this module (from forge). Looks like "graylog::repository -> $version" has no effect. Changing the value from "2.1" to "2.2" does not change the repo url in file /etc/yum.repos.d/graylog.repo.

Edit: same issue at the master branch

Cheers

**Comment by marcinbojko** [comment]
Second to that.

**Comment by lukaszpatyra** [comment]
+1

**Comment by k2patel** [comment]
i have submitted PR #12 to fix this. Hope fully merged tagged quickly.
Thank you.
