### ISSUE TITLE
Puppet Forge Release but Missing Tag in Repo

### ISSUE THREAD

**Issue by johnzimm** [Graylog2/puppet-graylog#13]
The entry at https://forge.puppet.com/graylog/graylog/changelog states the current release is 0.3.0.  There is no tag here for that release: https://github.com/Graylog2/puppet-graylog/tags.

**Comment by bernd** [comment]
@johnzimm Thank you for the report. I just released 0.4.0 and also pushed the 0.3.0 tag. Sorry about that!
