### ISSUE TITLE
Puppetlabs-apt dependency < 3.0.0

### ISSUE THREAD

**Issue by allangood** [Graylog2/puppet-graylog#16]
Please, update this dependency:
puppetlabs/apt (>= 2.2.2 < 3.0.0)

Puppetlabs/apt is version 4.1.0 now.

Thank you.

**Comment by DontPanic345** [comment]
Do you know if installing with `--ignore-dependencies` works?

**Comment by allangood** [comment]
Yes, it is working like a charm. I installed ignoring dependencies and no problem at all.
Regards

**Comment by robertmbaker** [comment]
I would just like to add a second confirmation. Using `--ignore-dependencies` works, and the module will install a graylog instance.

Please consider updating the apt dependency.

Thank you!

**Comment by llauren** [comment]
Oh please please fix this. Using `--ignore-dependencies` is an ugly hack. This results in me using a locally edited `metadata.json` which allows a current version of `puppetlabs-apt`, which means i need to upgrade the graylog module by `force` :(

**Comment by bernd** [comment]
We adjusted the dependency requirement to allow version 4.x as well.
