### ISSUE TITLE
elasticsearch/elasticsearch deprecated

### ISSUE THREAD

**Issue by bconner22** [Graylog2/puppet-graylog#17]
Hello, https://forge.puppet.com/elasticsearch/elasticsearch is deprecated, replaced by https://forge.puppet.com/elastic/elasticsearch.  Do you know if it's ok to use the new one with puppet-graylog?

**Comment by dnsmichi** [comment]
Just do it. It works fine here, the module was revamped and renamed. One thing to keep in mind - stick with 5.x, not sure if Graylog already is compatible with 6.x.

**Comment by bernd** [comment]
@bconner22 Thanks for the heads up. I replaced the references in the README file.
