### ISSUE TITLE
Feature Suggestion: Add capability for installation behind proxy (yum)

### ISSUE THREAD

**Issue by jsimpso** [Graylog2/puppet-graylog#19]
It would be great if the puppet module for Graylog supported the option to specify a proxy to be written into the yum repo file, as Elasticsearch and MongoDB do.

I'll happily submit a pull request to enable this functionality - it's the only thing breaking my setup flow at the moment!

Cheers

**Comment by bernd** [comment]
This has been implemented in #20.
