### ISSUE TITLE
Notify graylog service if /etc/graylog/server/server.conf has been modified.

### ISSUE THREAD

**Issue by jurim76** [Graylog2/puppet-graylog#2]
Add "notify => Service['graylog-server']" option for file { '/etc/graylog/server/server.conf' resource in server.pp

**Comment by mhutter** [comment]
This is already implemented in https://github.com/Graylog2/puppet-graylog/blob/master/manifests/server.pp#L56

**Comment by bernd** [comment]
Closing this because the service is already notified.
