### ISSUE TITLE
'Unknown function length'

### ISSUE THREAD

**Issue by bschaefer99** [Graylog2/puppet-graylog#23]
I'm at a loss as to why this isn't working.

First thing i should point out, on forge.puppet.com, the stdlib version required is listed as 4.11. We were on 4.14, so i thought we were good to go; however, i got this error:
`Error: Unknown function length at /vagrant/modules/graylog/manifests/server.pp:23`

A little digging, and i see that the length function was added in stdlib 4.16.

Okay, i'll update stdlib. Well, that's been done - `puppet module list` shows `puppetlabs-stdlib (v4.24.0)`.  And yet i'm still getting the same `Unknown function length` error.

We're on puppet 3.8.5, the latest supported in Ubuntu 16.04 LTS.

**Comment by ydeenekamp** [comment]
I have the same issue:

Puppet 3.8.7
stdlib 4.24.0
graylog 0.6.0

**Comment by ThisIsQasim** [comment]
Has there been any update on this?

**Comment by bernd** [comment]
We will bump the minimum version requirement for stdlib to 4.16. Not sure what else we can do, sorry.
