### ISSUE TITLE
Why is show_diff forced to true?

### ISSUE THREAD

**Issue by diranged** [Graylog2/puppet-graylog#24]
https://github.com/Graylog2/puppet-graylog/blob/3023b274b5308bbe8827c4c4becc7faa8762129e/manifests/server.pp#L43

First, the `File[]` resource in Puppet defaults to `true` here. Second, by forcing this to true, you make it difficult for us to disable this. The `server.conf` file includes unencrypted secrets (`password_secret`) that we do not want to see in our log files when we run Puppet.

**Comment by bernd** [comment]
@diranged Good catch! I think this was a leftover from debugging. I will remove it.

Thank you!
