### ISSUE TITLE
Gentoo & Sabayon support.

### ISSUE THREAD

**Issue by necrose99** [Graylog2/puppet-graylog#29]
https://forge.puppet.com/gentoo/portage

https://packages.gentoo.org/. 
app-admin/graylog2,  

Energe -bkv app-admin/greylog2 
(Build,  use or fetch package/s if prebuilt , verbose)

Can control via above puppet models Gentoo Portage 

Gentoo family,  includes,  calculate , Redcore, ChromeOS, Sabayon,  Coreos... Funtoo ,Clover , etc. 

https://forge.puppet.com/optiz0r/sabayon
Takes care of entropy Package Management 
(Sabayon is Derived of Gentoo) 
(Equo up , equo u , equo I  app-admin/greylog2 .)
Though  emerge Portage is useable , it can muck up a Sabayon Instal at times.

**Comment by necrose99** [comment]
https://packages.gentoo.org/packages/app-admin/graylog 
https://packages.gentoo.org/packages/dev-db/mongodb
https://packages.gentoo.org/packages/app-misc/elasticsearch 
hears the updated gentoo package/s .. 

**https://forge.puppet.com/modules/gentoo/portage/readme** (**dependency add**) 


```
  package_use { 'app-admin/graylog    dev-db/mongodb  app-misc/elasticsearch  ':
    target => 'puppet',
   ensure  => present,
  }
```

add packages ... via portage... 

most other puppet/bolt options should then apply standard Linux compatible configs ... 

this should suffice for appending gentoo support

**Comment by bernd** [comment]
We don't plan to add Gentoo & Sabayon support to the Puppet module because we don't support these operating systems.
