### ISSUE TITLE
Apt repo class does not work properly

### ISSUE THREAD

**Issue by not-known** [Graylog2/puppet-graylog#30]
The apt repo class doesn't work if /etc/apt/apt.conf.d/01proxy is not present at all.

Error: /Stage[main]/Graylog::Repository::Apt/File_line[Remove graylog config from apt proxy file]: Could not evaluate: No such file or directory @ rb_sysopen - /etc/apt/apt.conf.d/01proxy

~~Workaround for now is to create an empty file but that's a bit ugly.~~
Workaround doesn't work either. Apt module removes the file if no proxy is configured.

**Comment by SirUrban** [comment]
Would be nice to have a new release soon to get rid of this bug.

**Comment by indygriffiths** [comment]
Just adding that this is also causing us some trouble upgrading so echoing the above

**Comment by bernd** [comment]
We just released version 0.9.0 of this module which should fix this issue.

Thank you for the report and the patience!
