### ISSUE TITLE
Update to allow for puppetlabs-apt > 7.x

### ISSUE THREAD

**Issue by jameskirsop** [Graylog2/puppet-graylog#37]
Please update the dependencies of this module to include `puppetlabs-apt` versions 7.x and higher which was first released in [April 2019](https://github.com/puppetlabs/puppetlabs-apt/compare/6.3.0...7.0.0).

**Comment by juju2112** [comment]
Should be fixed in https://github.com/Graylog2/puppet-graylog/pull/43.
