### ISSUE TITLE
Permissions on /etc/graylog/server are wrong

### ISSUE THREAD

**Issue by kwisatz** [Graylog2/puppet-graylog#7]
While the server.conf belongs to user graylog, the directory itself belongs to root.

This leads to the server not being able to create a node-id file, which is usually related to connectivity issues to elasticsearch.

Chown'ing the server directory to graylog fixed the issue.

**Comment by mhutter** [comment]
Creation of `node-id` is handled in the [post-install script of the OS package](https://github.com/Graylog2/fpm-recipes/blob/master/recipes/graylog-server/files/post-install#L40-L41)

**Comment by kwisatz** [comment]
Well OK, then I'd need to recheck why it didn't work in my case.

On December 6, 2016 1:47:52 PM GMT+01:00, Manuel Hutter <notifications@github.com> wrote:
>Creation of `node-id` is handled in the [post-install script of the OS
>package](https://github.com/Graylog2/fpm-recipes/blob/master/recipes/graylog-server/files/post-install#L40-L41)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Graylog2/puppet-graylog/issues/7#issuecomment-265141660

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kwisatz** [comment]
I'll close this and will reopen a new ticket should I ever experience the same problem again. This time at least I know what to look for.
