### ISSUE TITLE
metadata.json outputs module error with 'puppet module list'

### ISSUE THREAD

**Issue by tdac** [Graylog2/puppet-graylog#8]
Puppet-GrayLog 0.2.1 gives the following output when `puppet module list` is run:

`$ puppet module list | egrep 'stdlib|apt'`
`Warning: Missing dependency 'puppetlabs-apt':`
`  'graylog-graylog' (v0.2.1) requires 'puppetlabs-apt' (>= 2.2.2 < 3.0.0)`
`Warning: Missing dependency 'puppetlabs-stdlib':`
`  'graylog-graylog' (v0.2.1) requires 'puppetlabs-stdlib' (>= 4.11.0 < 5.0.0)`
`âââ puppetlabs-apt (v2.3.0)`
`âââ puppetlabs-stdlib (v4.13.1)`

This can be fixed by changing metadata.json:

` "dependencies": [`
`-    {"name":"puppetlabs-stdlib","version_requirement":">= 4.11.0 < 5.0.0"},`
`-    {"name":"puppetlabs-apt","version_requirement":">= 2.2.2 < 3.0.0"}`
`+   {"name":"puppetlabs/stdlib","version_requirement":">= 4.11.0 < 5.0.0"},`
`+   {"name":"puppetlabs/apt","version_requirement":">= 2.2.2 < 3.0.0"}`
 ` ],`

(test on Ubuntu 16.04, Puppet 3.8.5)

**Comment by bernd** [comment]
Thank you for the report, this has been fixed in f9b979a.
