### ISSUE TITLE
Wrong repo URL

### ISSUE THREAD

**Issue by danieltownend-ha247** [Graylog2/puppet-graylog#9]
Looks like the repo URL has changed from,

https://downloads.graylog.org/repo/debian/

To 

https://downloads.graylog2.org/repo/debian/

I've changed this locally in manifests/params.pp but needs changing in the master.

**Comment by danieltownend-ha247** [comment]
Sorry, quick correction. The URL's need to be

  $repository_url = $::osfamily ? {
    'debian' => 'https://downloads.graylog2.org/repo/debian/',
    'redhat' => "https://downloads.graylog2.org/repo/el/${repository_release}/${major_version}/\$basearch/",
    default  => fail("${::osfamily} is not supported!"),
  }

And I also get a SSL error due to the domain change.
W: Failed to fetch https://downloads.graylog2.org/repo/debian/dists/stable/2.1/binary-amd64/Packages  SSL: certificate subject name (*.graylog.org) does not match target host name 'downloads.graylog2.org'

**Comment by bernd** [comment]
The current URLs in the module work fine. Please see #5 for more information on the topic.
